connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: workshops
  password: 'workshops'
  template: template0

development:
  <<: *connection
  database: template_development

test: &test
  <<: *connection
  database: template_test